name: clojure-app

services:
  appserver:
    type: compose

    services:
      image: acobster/lando-clojure:cli-tools
      command: clojure -m app

  # Look Ma, no dbhost!

  nginx:
    type: nginx:1.14
    webroot: resources/public
    ssl: true

    config:
      server: lando/nginx.conf

    overrides:
      depends_on:
        - appserver

proxy:
  nginx:
    - clojure-app.lndo.site
